######################################################################
# Automatically generated by qmake (3.0) Sun Jan 31 22:41:28 2016
######################################################################

TEMPLATE = app
TARGET = hw1
INCLUDEPATH += .

# Input
HEADERS += birthday.h birthdaylist.h
SOURCES += birthday.cpp birthdaylist.cpp main.cpp

# allow nullptr
QMAKE_CXXFLAGS += -std=c++0x
