######################################################################
# Automatically generated by qmake (3.0) Sun Feb 7 01:27:21 2016
######################################################################

TEMPLATE = app
TARGET = birthday
INCLUDEPATH += .

# Input
HEADERS += birthday.h birthdaylist.h
SOURCES += birthday.cpp birthdaylist.cpp main.cpp

# allow nullptr
QMAKE_CXXFLAGS += -std=c++0x
