######################################################################
# Automatically generated by qmake (3.0) Sat Jan 30 14:54:24 2016
######################################################################

TEMPLATE = app
TARGET = hw1
INCLUDEPATH += .

# Input
SOURCES += main.cpp
